version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo deploying to $TARGET_BUCKET_NAME
      - echo note target address is $TARGET_ADDRESS
      - npm run deploy
artifacts:
  base-directory: public
  files:
    - '**/*'
  discard-paths: no
cache:
  paths:
    - '.cache/*'
    - 'node_modules/*'
    - 'public/*'